add_layout
dima0208/Inteo_m pull request #1
Opened 2023-03-21 13:11 UTC by dima0208

2023-03-21 15:42 UTC, ArturNagaycev reviewed
Good job! 👍 

I would advise you to create directive `@layer base ` with default fonts to avoid writing them in every class

2023-03-21 15:42 UTC, a-nahaitsev commented on src/App.jsx
> +      <div className='main'>
Where did you style these classes? I can't find

And also in this case instead of `div` use the semantic tag `main`

2023-03-21 15:42 UTC, a-nahaitsev commented on src/components/Header/Header.jsx
> +        <a className='' href='#'>
why don't you remove `className=''` ?

2023-03-21 15:42 UTC, a-nahaitsev commented on src/components/Button/Button.jsx
> +      {children}
Maybe rename this prop to `text`, for example. It will be more understandable

2023-03-22 09:17 UTC, ArturNagaycev approved these changes

2023-03-23 17:39 UTC, IgorNovikov10 requested changes

2023-03-23 17:39 UTC, IgorNovikov10 commented on src/components/AwardsHeader/AwardsHeader.jsx
> +export const AwardsHeader = () => {
Does it really make sense to have this as a component?

The idea for the component to be reusable

You can at least take a text as a prop and give it more generic name for example `Header` or `ListHeader`

2023-03-23 17:39 UTC, IgorNovikov10 commented on src/components/BaseText/BaseText.jsx
> +  const sizes = {
please do not keep variables that do not depend on state/props in the body of the component - it's static data

2023-03-23 17:39 UTC, IgorNovikov10 commented on src/components/BaseText/BaseText.jsx
> +  size: PropTypes.string.isRequired,
use PropTypes.oneOf if you have static list of the available values

2023-03-23 17:40 UTC, IgorNovikov10 requested changes

2023-03-23 17:40 UTC, IgorNovikov10 commented on src/components/Button/Button.jsx
> +  size: PropTypes.string.isRequired,
the same here: use PropTypes.oneOf if you have static list of the available values

2023-03-23 17:40 UTC, IgorNovikov10 commented on src/components/Button/Button.jsx
> +  const sizes = {
please do not keep variables that do not depend on state/props in the body of the component - it's static data

2023-03-23 17:51 UTC, IgorNovikov10 requested changes

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/components/EyebrowTitle/EyebrowTitle.jsx
> +  browPlace: PropTypes.string.isRequired,
the same here: use PropTypes.oneOf if you have static list of the available values

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/components/Footer/Footer.jsx
> +  const socialNetworks = [
please do not keep variables that do not depend on state/props in the body of the component - it's static data

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/components/Header/Header.jsx
> +              <a
use unordered list to print out menu items

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/components/Title/Title.jsx
> +  const sizes = {
please do not keep variables that do not depend on state/props in the body of the component - it's static data

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/components/Title/Title.jsx
> +  size: PropTypes.string.isRequired,
the same here: use PropTypes.oneOf if you have static list of the available values

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/sections/Awards/Awards.jsx
> +            <div
use unordered list to print out awards items

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/sections/Awards/Awards.jsx
> +  const awards = [
please do not keep variables that do not depend on state/props in the body of the component - it's static data

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/sections/Metric/Metric.jsx
> +  const metrics = [
please do not keep variables that do not depend on state/props in the body of the component - it's static data

2023-03-23 17:51 UTC, IgorNovikov10 commented on src/sections/Works/Works.jsx
> +  const latestWork = {
please do not keep variables that do not depend on state/props in the body of the component - it's static data

2023-03-30 17:52 UTC, IgorNovikov10 requested changes

2023-03-30 17:52 UTC, IgorNovikov10 commented on src/components/Button/Button.jsx
> +  size: PropTypes.oneOf(['normal', 'big']).isRequired,
you can use `PropTypes.oneOf(Object.keys(sizes)).isRequired`

to keep the source of truth in `sizes` variable

2023-03-30 17:52 UTC, IgorNovikov10 commented on src/components/EyebrowTitle/EyebrowTitle.jsx
> +  browPlace: PropTypes.oneOf(['before', 'after']).isRequired,
you can use PropTypes.oneOf(Object.keys(browPlace)).isRequired

to keep the source of truth in `browPlace` variable

the same in other places where you use dictionary with possible values for some properties

2023-04-19 07:24 UTC, merged